# Generated by Django 4.0.5 on 2023-09-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default2.jpg', upload_to='user_profile_pics'),
        ),
    ]
