# Generated by Django 4.1.7 on 2023-03-18 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='bing_delivered',
            new_name='being_delivered',
        ),
    ]
