# Generated by Django 4.0.5 on 2023-10-20 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0004_alter_accepttask_receiver_alter_bidder_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReportTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200)),
                ('no_of_pages', models.IntegerField(default=0)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_sender', to=settings.AUTH_USER_MODEL)),
                ('task_bidders', models.ManyToManyField(blank=True, related_name='lab_report_bidders', to='tasks.bidder')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryTask',
            fields=[
                ('tracking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_address', models.TextField()),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_address', models.TextField()),
                ('delivery_date', models.DateField(auto_now=True)),
                ('delivery_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('package_description', models.TextField(blank=True, null=True)),
                ('package_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
