# Generated by Django 4.0.5 on 2023-10-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_labreporttask_deliverytask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labreporttask',
            old_name='slug',
            new_name='task_slug',
        ),
    ]
