# Generated by Django 4.0.5 on 2023-10-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0006_rename_slug_labreporttask_task_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreporttask',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_report_receiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
