# Generated by Django 4.0.5 on 2023-10-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_labreporttask_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='labreporttask',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
