# Generated by Django 4.0.5 on 2023-10-20 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_labreporttask_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreporttask',
            name='no_of_pages',
            field=models.IntegerField(),
        ),
    ]
