# Generated by Django 4.0.5 on 2023-10-20 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0010_alter_labreporttask_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundryTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_slug', models.SlugField()),
                ('clothes', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('extra_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='laundry_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_sender', to=settings.AUTH_USER_MODEL)),
                ('task_bidders', models.ManyToManyField(blank=True, related_name='laundry_bidders', to='tasks.bidder')),
            ],
        ),
    ]
