# Generated by Django 4.1.7 on 2023-04-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_bidder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bidder',
        ),
    ]
