# Generated by Django 4.1.7 on 2023-04-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_bidders',
            field=models.ManyToManyField(related_name='single_task_bidders', to='tasks.bidder'),
        ),
    ]
