# Generated by Django 4.1.7 on 2023-05-01 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_remove_task_receiver_task_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_bidders',
            field=models.ManyToManyField(blank=True, null=True, related_name='single_task_bidders', to='tasks.bidder'),
        ),
    ]
