# Generated by Django 4.1.7 on 2023-05-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0019_alter_task_task_bidders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='messenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='the_task_messenger', to=settings.AUTH_USER_MODEL),
        ),
    ]
