# Generated by Django 4.1.7 on 2023-06-04 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0024_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskreview',
            name='errandee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskreview',
            name='errander',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_errander', to=settings.AUTH_USER_MODEL),
        ),
    ]
