# Generated by Django 4.1.7 on 2023-06-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_shop_description_shop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(default='me'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='rating',
            field=models.CharField(default=10, max_length=10),
        ),
    ]
