# Generated by Django 4.1.7 on 2023-06-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_shop_slug_alter_shop_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='tasks.task'),
        ),
    ]
