# Generated by Django 4.1.7 on 2023-06-13 16:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0031_alter_shop_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='subscribers',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
