# Generated by Django 4.1.7 on 2023-06-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_alter_shop_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
