# Generated by Django 4.1.7 on 2023-06-21 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0034_shop_owner_alter_shop_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='shop_documents')),
            ],
        ),
        migrations.CreateModel(
            name='ShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='shop_images')),
            ],
        ),
        migrations.CreateModel(
            name='ShopProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('documents', models.ManyToManyField(to='tasks.shopdocuments')),
                ('other_images', models.ManyToManyField(blank=True, to='tasks.shopimages')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tasks.shop')),
            ],
        ),
    ]
