# Generated by Django 4.1.7 on 2023-06-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_task_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='tasks.keyword'),
        ),
    ]
